#!/bin/bash

#
# ---------------------------------------------------------
# Comments & optional setting
# ---------------------------------------------------------
# INPUT1 = Delta 
# INPUT2 = MD - New Planck's scale
# INPUT3 = Amount
# INPUT4 = INDEX 

#
# ---------------------------------------------------------
# LSF parameters
# ---------------------------------------------------------
#
echo ""
echo "Job is running on `uname -a`"
echo "Job started on `date`"
echo ""
#echo "Job has been submitted from : " $LS_SUBCWD


# . /afs/cern.ch/sw/lcg/external/gcc/4.8/x86_64-slc6/setup.sh
# . /afs/cern.ch/sw/lcg/app/releases/ROOT/5.34.32/x86_64-slc6-gcc48-opt/root/bin/thisroot.sh

#
#----------------------------------------------------------
# S e t   t h e   r u n t i m e   e n v i r o n m e n t
#----------------------------------------------------------
#
echo "Step 1 : Setting the environment"

# Set Path
SCRATCH_SRC="/afs/cern.ch/work/s/sekin/private/Project/FCC_hh_100TeV/FCC_Project/Simulation/Signal/ADD"
CODE_SRC=${SCRATCH_SRC}/Generation/CODE
WORKDIRME=${SCRATCH_SRC}/Processes
PYTHIA8DIR=/home/orion/Software/Pythia8/pythia8186   # must edit
DATADIR="/afs/cern.ch/work/s/sekin/private/Project/FCC_hh_100TeV"
DELPHESDIR="/afs/cern.ch/work/s/sekin/private/Software/Delphes-3.3.2"
WORKDIR=${WORKDIRME}
#WORKDIR_ME=${SCRATCH_SRC}/Processes_GEN
#WORKDIR=${WORKDIR_ME}

# Set Software
. /afs/cern.ch/sw/lcg/external/gcc/4.8/x86_64-slc6/setup.sh
. /afs/cern.ch/sw/lcg/app/releases/ROOT/5.34.32/x86_64-slc6-gcc48-opt/root/bin/thisroot.sh
#SCRAM_ARCH=slc6_amd64_gcc481

echo "- - - - - PATH SETTING- - - - -"
echo "SCRAM_ARCH is : " ${SCRAM_ARCH}
echo "CODE_SRC is : " ${CODE_SRC}
echo "WorkDir    is : " ${WORKDIR}
echo "Disk space on this batch machine:"
df -h


#
#----------------------------------------------------------
# Run INPUT
#----------------------------------------------------------
#
echo "Step 2 : Run"
###########################################################################################
## Step-1: Setting Variables                                                              #
###########################################################################################

echo "Start Step-1: "

cd ${WORKDIR}
#SCRAM_ARCH=slc6_amd64_gcc472

cd ${PYTHIA8DIR}

cp -a FCC_ADD_Template INPUT1_INPUT2_INPUT3_INPUT4

cd INPUT1_INPUT2_INPUT3_INPUT4

#source config.sh

sed s/IN1/INPUT1/g ADD_pythia.cc > temp
mv temp ADD_pythia.cc

sed s/IN2/INPUT2/g ADD_pythia.cc > temp
mv temp ADD_pythia.cc

sed s/IN3/INPUT3/g ADD_pythia.cc > temp
mv temp ADD_pythia.cc

sed s/IN4/INPUT4/g ADD_pythia.cc > temp
mv temp ADD_pythia.cc

################################################################################################################
###########################################################################################
## Step-2: Running Pythia                                                                 #
###########################################################################################

echo "Start Step-2: "

make ADD_pythia
./ADD_pythia.exe > pythia_INPUT1_INPUT2_INPUT3_INPUT4.log

cd ../

mv INPUT1_INPUT2_INPUT3_INPUT4 ${WORKDIR} 
cd ${WORKDIR}/INPUT1_INPUT2_INPUT3_INPUT4

##########################################################################################
# Step-3: Running DELPHES                                                                #
##########################################################################################

echo "Start Step-3: "

#-----------Download necessory files from Delphes directory-------------

cp -a ${CODE_SRC}/../Analysis_Code.C .
cp -a ${DELPHESDIR}/libDelphes.so .
cp -a ${DELPHESDIR}/DelphesHepMC .
cp -a ${DELPHESDIR}/cards/delphes_card_FCC_hh_rfast002.tcl .


#----------Running Delphes--------

echo "Running Delphes"

./DelphesHepMC delphes_card_FCC_hh_rfast002.tcl tev100_pythia8_ADD_INPUT1_INPUT2_INPUT3_INPUT4.root pythia_ADD_INPUT1_INPUT2_INPUT3_INPUT4.hep

rm pythia_ADD_INPUT1_INPUT2_INPUT3_INPUT4.hep 

##---------------------------------------------Analysis Part---------------------------------

mv tev100_pythia8_ADD_INPUT1_INPUT2_INPUT3_INPUT4.root FileLoad.root 

for plotN in `seq 0 7` ; do
    root -l <<EOF
        .L Analysis_Code.C
        Analysis_Code("FileLoad.root",${plotN},0)
        .q
EOF
    mv Monojet.root Analysis_ADD_INPUT1_INPUT2_INPUT3_INPUT4_${plotN}.root
    mv Monojet.txt  Analysis_ADD_INPUT1_INPUT2_INPUT3_INPUT4_${plotN}.txt
done

rm libDelphes.so
rm DelphesHepMC

#
# Clear job and log
#----------------------------------------------------------
#-----------------------------Move File--------------------------------
mv FileLoad.root tev100_pythia8_ADD_INPUT1_INPUT2_INPUT3_INPUT4.root 
mv tev100_pythia8_ADD_INPUT1_INPUT2_INPUT3_INPUT4.root ${DATADIR}/ADD
mv Analysis_ADD_* ${SCRATCH_SRC}/Processes


cd ${WORKDIR}

echo ""
echo "Job end `date`"
echo ""

exit ${status}
    #==============================End Of Program======================================
